import Head from 'next/head';
import Link from 'next/link';
import {
  ApolloClient,
  InMemoryCache,
  gql,
} from "@apollo/client";

import Layout from '@components/Layout';
import Header from '@components/Header';
import Container from '@components/Container';
import Button from '@components/Button';

import styles from '@styles/Page.module.scss'
import AddProductToCartButton from '@components/AddProductToCartButton';

export default function Category({ category, products }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>{category.name}</h1>

        <h2>Products</h2>

        <ul className={styles.products}>
          {products.map(product => (
            <li key={product.id}>
              <Link href={`/products/${product.slug}`}>
                <a>
                  <div className={styles.productImage}>
                    <img
                      width={product.image.width}
                      height={product.image.height}
                      src={product.image.url}
                      alt=""
                    />
                  </div>
                  <h3 className={styles.productTitle}>
                    {product.name}
                  </h3>
                  <p className={styles.productPrice}>
                    ${product.price?.toFixed(2)}
                  </p>
                </a>
              </Link>
              <p>
                <AddProductToCartButton
                  productId={product.id}
                  productName={product.name}
                  productPrice={product.price}
                  productSlug={`/products/${product.slug}`}
                  imageUrl={product.image.url}
                />
              </p>
            </li>
          ))}
        </ul>
      </Container>
    </Layout>
  )
}

export async function getStaticPaths() {
  const client = new ApolloClient({
    uri: "https://api-sa-east-1.hygraph.com/v2/clcy4n6d72s5y01t5gcbohop0/master",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query CATEGORIES {
        categories {
          id
          slug
        }
      }
    `,
  });

  const paths = data.categories.map(category => {
    return {
      params: {
        categorySlug: category.slug,
      }
    };
  });

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const client = new ApolloClient({
    uri: "https://api-sa-east-1.hygraph.com/v2/clcy4n6d72s5y01t5gcbohop0/master",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query CATEGORY($categorySlug: String) {
        category(where: { slug: $categorySlug }) {
          id
          name
          slug
          products {
            id
            name
            slug
            price
            image
          }
        }
      }
    `,
    variables: {
      categorySlug: params.categorySlug,
    }
  });

  return {
    props: {
      category: data.category,
      products: data.category.products,
    }
  }
}
