import Head from 'next/head'
import {
  ApolloClient,
  InMemoryCache,
  gql,
} from "@apollo/client";

import Layout from '@components/Layout';
import Container from '@components/Container';
import AddProductToCartButton from '@components/AddProductToCartButton';

import styles from '@styles/Product.module.scss'

export default function Product({ product }) {
  return (
    <Layout>
      <Head>
        <title>Space Jelly Gear: {product.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <div className={styles.productWrapper}>
          <div className={styles.productImage}>
            <img src={product.image.url} width={product.image.width} height={product.image.height} alt="" />
          </div>
          <div className={styles.productContent}>
            <h1>{product.name}</h1>
            <div className={styles.productDescription} dangerouslySetInnerHTML={{
              __html: product.description?.html,
            }} />
            <p className={styles.productPrice}>
              ${product.price}
            </p>
            <p className={styles.productBuy}>
              <AddProductToCartButton
                productId={product.id}
                productName={product.name}
                productPrice={product.price}
                productUrl={`/products/${product.slug}`}
                imageUrl={product.image.url}
              />
            </p>
          </div>
        </div>
      </Container>
    </Layout>
  )
}

export async function getStaticPaths() {
  const client = new ApolloClient({
    uri: "https://api-sa-east-1.hygraph.com/v2/clcy4n6d72s5y01t5gcbohop0/master",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query PATHS_PRODUCTS {
        products {
          name
          price
          slug
          image
          description {
            html
          }
        }
      }
    `,
  });

  const paths = data.products.map(product => {
    return {
      params: {
        productSlug: product.slug,
      }
    };
  });

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const client = new ApolloClient({
    uri: "https://api-sa-east-1.hygraph.com/v2/clcy4n6d72s5y01t5gcbohop0/master",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query PRODUCT($productSlug: String) {
        product(where: { slug: $productSlug }) {
          id
          name
          price
          image
          description {
            html
          }
        }
      }
    `,
    variables: {
      productSlug: params.productSlug,
    }
  });

  return {
    props: {
      product: data.product,
    }
  }
}
