import Head from 'next/head'
import { gql } from "@apollo/client";

import Layout from '@components/Layout';
import Container from '@components/Container';
import AddProductToCartButton from '@components/AddProductToCartButton';
import CloudinaryImage from '@components/CloudinaryImage';
import hygraph from '@api/hygraph';
import styles from '@styles/Product.module.scss'
import avoidTooManyRequestsError from "@util/avoidTooManyRequestsError";

export default function Product({ product }) {
  return (
    <Layout>
      <Head>
        <title>Space Jelly Gear: {product.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <div className={styles.productWrapper}>
          <div className={styles.productImage}>
            <CloudinaryImage
              publicId={product.image.public_id}
              width={product.image.width}
              height={product.image.height}
              alt=""
            />
          </div>
          <div className={styles.productContent}>
            <h1>{product.name}</h1>
            <div className={styles.productDescription} dangerouslySetInnerHTML={{
              __html: product.description?.html,
            }} />
            <p className={styles.productPrice}>
              ${product.price}
            </p>
            <p className={styles.productBuy}>
              <AddProductToCartButton
                productId={product.id}
                productName={product.name}
                productPrice={product.price}
                productUrl={`/products/${product.slug}`}
                cloudinaryPublicImageId={product.image.public_id}
              />
            </p>
          </div>
        </div>
      </Container>
    </Layout>
  )
}

export async function getStaticPaths({ locales }) {
  const { data } = await hygraph.query({
    query: gql`
      query PATHS_PRODUCTS {
        products {
          name
          price
          slug
          image
          description {
            html
          }
        }
      }
    `,
  });

  const paths = data.products.flatMap(product => {
    return locales.map(locale => ({
      locale,
      params: {
        productSlug: product.slug,
      }
    }))
  });

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params, locale }) {
  await avoidTooManyRequestsError();

  const { data } = await hygraph.query({
    query: gql`
      query PRODUCT($productSlug: String, $locale: Locale!) {
        product(where: { slug: $productSlug }, locales: [$locale]) {
          id
          name
          price
          image
          description {
            html
          }
        }
      }
    `,
    variables: {
      productSlug: params.productSlug,
      locale: locale.replace('-', '_'),
    }
  });

  return {
    props: {
      product: data.product,
    }
  }
}
